### PR TITLE
fix / update styles

### PR DESCRIPTION
**Pull request by armano2**
Codecov had some class style changes and current style is no longer correct, this is fixing issues.

image

image

image

image

image

image

### CODE REVIEW

**Comment by dragonmux** [comment]
Hello, and sorry for the delay responding to you.

Thank you for this patch set. Things this patch does right:

* Introduces some of its changes as additions at the end - thank you
* Comments. I was very lax to add them originally.

However I have a couple of problems with it which mean I cannot in good conscience just accept it as is.. namely:

* You reformatted the entire source (not terrible in itself) while also changing the CSS (I can't see what changed!) so I cannot review the changes as I cannot locate them.
* You've used spaces when I specifically used tabs and you've used { on the same line where I specifically used { on a new. Please respect the existing source style if you are going to reformat it.

This may not be the popular opinion, however my original formatting(!) is routed in a good reason: It's a hard-won balance between human readability vs parsing speed, as space-based whitespace is an extreme slowdown for any parser as the parser has to step through and inspect it character by character.
This is combined with being super unfriendly to editors that don't reinterpret spaces as if they were written as tabs (I use editors that are dumb to this).

I am interested in accepting this patch if you could please remedy some of the issues presented here.

**Comment by armano2** [comment]
@DX-MON  about tab vs spaces (there was no guideline but i created now .editorconfig file for this)

this is "wierd" formatting, but i restored it to original format.

**Comment by dragonmux** [comment]
Much appreciated, @armano2 - I freely admit I'm not used to building .editorconfig files for my projects, so I'm grateful you've put one together.

I will review the diff properly in the morning, though a cursory glance says it looks reasonable.
I may ask you tweak some of the background colours back to their grey neutral tones as (and I should write this in the README) I set it up to be neutral to those who suffer from blue issues (f.lux neutral), but that's really a cosmetic thing.

That said, and as has been pointed out to me offline, Stylus/Stylish does support colour configurables, so I might convert background and foreground colours to be tweak-able for those who want a particular tint on the theme.

**Comment by dragonmux** [comment]
Thanks for the fixes you made - I've now finally had time to review them and I'm happy with most of it. I can fix the other small details such as version number bumps from here, so I'm happy to take these changes.

**Pull request merged**
